name: Unpack ZIP To Repo

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Unzip OfflineSkins.zip
        run: unzip -o OfflineSkins.zip -d .

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .

          git commit -m "Unpacked OfflineSkins.zip" || echo "No changes"

          git push
